### ISSUE TITLE
composer create-project aborts with PHP Fatal error:  Uncaught Error: Call to a member function getVersions() on null

### ISSUE THREAD

**Issue by fogs** [symfony/website-skeleton#244]
When creating a new project using `composer create-project symfony/website-skeleton my_project_name` as per https://symfony.com/doc/current/setup.html I am getting the following error:
```
root@2ec2e6ed2015:/# composer create-project symfony/website-skeleton my_project_name
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Installing symfony/website-skeleton (v4.3.99)
    Failed to download symfony/website-skeleton from dist: The zip extension and unzip command are both missing, skipping.
Your command-line PHP is using multiple ini files. Run `php --ini` to show them.
    Now trying to download from source
  - Installing symfony/website-skeleton (v4.3.99): Cloning b88a14bcaa from cache
Created project in my_project_name
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
    Failed to download symfony/flex from dist: The zip extension and unzip command are both missing, skipping.
Your command-line PHP is using multiple ini files. Run `php --ini` to show them.
    Now trying to download from source
  - Installing symfony/flex (v1.4.8): Cloning f5bfc79c1f from cache
Symfony operations: 1 recipe (29b3f51d3d6c7265767b477cce45e405)
  - Configuring symfony/flex (>=1.0): From github.com/symfony/recipes:master
Loading composer repositories with package information
Updating dependencies (including require-dev)
PHP Fatal error:  Uncaught Error: Call to a member function getVersions() on null in /my_project_name/vendor/symfony/flex/src/Cache.php:118
Stack trace:
#0 /my_project_name/vendor/symfony/flex/src/Cache.php(58): Symfony\Flex\Cache->getVersions()
#1 /my_project_name/vendor/symfony/flex/src/TruncatedComposerRepository.php(41): Symfony\Flex\Cache->removeLegacyTags(Array)
#2 /usr/share/php/Composer/Repository/ComposerRepository.php(339): Symfony\Flex\TruncatedComposerRepository->fetchFile('http://packagis...', 'provider-symfon...', '73153d0f92fa8ce...', false)
#3 /my_project_name/vendor/symfony/flex/src/Flex.php(538): Composer\Repository\ComposerRepository->whatProvides(Object(Composer\DependencyResolver\Pool), 'symfony/dotenv', false)
#4 /usr/share/php/Composer/DependencyResolver/Pool.php(204): class@anonymous->whatProvides(Object(Composer\DependencyResolver\Pool), 'symfony/dotenv', false)
#5 /usr/share/php/Composer/DependencyResolver/Pool.php(193): Composer\DependencyResolver\Pool->computeWhatProvides('symfony/dotenv', Object(Co in /my_project_name/vendor/symfony/flex/src/Cache.php on line 118
```
Something similar happens when running `symfony new my_project_namex --full` instead:
```
root@2ec2e6ed2015:/# symfony new my_project_namex --full      
* Creating a new Symfony project with Composer
  (running /usr/bin/composer create-project symfony/website-skeleton my_project_namex)

Do not run Composer as root/super user! See https://getcomposer.org/root for details
Installing symfony/website-skeleton (v4.3.99)
    Failed to download symfony/website-skeleton from dist: The zip extension and unzip command are both missing, skipping.
Your command-line PHP is using multiple ini files. Run `php --ini` to show them.
    Now trying to download from source
  - Installing symfony/website-skeleton (v4.3.99): Cloning b88a14bcaa from cache
Created project in my_project_namex
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
    Failed to download symfony/flex from dist: The zip extension and unzip command are both missing, skipping.
Your command-line PHP is using multiple ini files. Run `php --ini` to show them.
    Now trying to download from source
  - Installing symfony/flex (v1.4.8): Cloning f5bfc79c1f from cache
Symfony operations: 1 recipe (aca9ac4c0c32b777b0710c0c1779e9f8)
  - Configuring symfony/flex (>=1.0): From github.com/symfony/recipes:master
Loading composer repositories with package information
Updating dependencies (including require-dev)

In VersionParser.php line 172:
                             
  Invalid version string ""  
                             

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]

                                                                                                            
  unable to run /usr/bin/composer create-project symfony/website-skeleton my_project_namex : exit status 1  
```

How to reproduce:

- `docker run -it ubuntu:18.04 bash`
- `apt update && apt install composer wget -y`    # chosen Europe/Amsterdam as timezone when asked
- then run either of the above commands

**Comment by derrabus** [comment]
Same as symfony/flex#571
